drop DATABASE BMS_DB;
create DATABASE BMS_DB1;

use BMS_DB1;

SHOW DATABASES; 

-- CUSTOMER_PERSONAL_INFO

CREATE TABLE CUSTOMER_PERSONAL_INFO (
    CUSTOMER_ID VARCHAR(5),
    CUSTOMER_NAME VARCHAR(50),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(50),
    ADDRESS VARCHAR(50),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(50),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    IDENTIFICATION_DOC_TYPE VARCHAR(20),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(10),
    CONSTRAINT CUST_PRRS_INFO_PK PRIMARY KEY (CUSTOMER_ID)
);

SELECT * FROM CUSTOMER_PERSONAL_INFO;

INSERT INTO  CUSTOMER_PERSONAL_INFO VALUES('1','VAISHNAVI','2002-01-26','SATISH KUMBHAR','SOLAPUR',7498696598,'vaishnavisatish9096@gmail.com','F','NO','ADHAR_CARD','1234','INDIAN');

INSERT INTO  CUSTOMER_PERSONAL_INFO VALUES('2','NEHA','2002-02-26','VINAYAK DIXIT','SOLAPUR',9096498934,'nehadixit9098@gmail.com','F','NO','PAN_CARD','123456','INDIAN');

INSERT INTO  CUSTOMER_PERSONAL_INFO VALUES('3','SHRUTI','2002-12-30','CHAVAN RAM','SANGLI',8459426248,'shrutichavan@gmail.com','F','YES','VOTER_CARD','3456','INDIAN');

INSERT INTO  CUSTOMER_PERSONAL_INFO VALUES('4','RAM','2002-11-12','SATISH TAKLE','NATEPUTE',5643728932,'ramtakle@gmail.com','M','YES','DRIVING_LICENCE_CARD','1234','INDIAN');

INSERT INTO  CUSTOMER_PERSONAL_INFO VALUES('5','VAISHNAVI','2002-01-26','SANTOSH KUMBHAR','KURBAVI',7498696598,'vaishnavisatish@gmail.com','F','NO','ADHAR_CARD','1234','INDIAN');

SELECT * FROM CUSTOMER_PERSONAL_INFO;

SHOW TABLES;



CREATE TABLE CUSTOMER_REFERENCE_INFO
(
CUSTOMER_ID VARCHAR(5),
REFERENCE_ACC_NAME VARCHAR(20),
REFERENCE_ACC_NO BIGINT(16),
REFERENCE_ACC_ADDRESS VARCHAR(50),
RELATION VARCHAR(25),
CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID)REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);

INSERT INTO CUSTOMER_REFERENCE_INFO VALUES ('1','SAVING_ACCOUNT','1234567','SOLAPUR','TEMPORY');

INSERT INTO CUSTOMER_REFERENCE_INFO VALUES ('2','SAVING_ACCOUNT','67890','MIRAJ','PERMANENT');

INSERT INTO CUSTOMER_REFERENCE_INFO VALUES ('3','CREDITANDDEBIT','109870','DHULE','TEMPORY');

INSERT INTO CUSTOMER_REFERENCE_INFO VALUES ('4','TEMPORY_ACCOUNT','156737','NATEPUTE','PERMANENT');

INSERT INTO CUSTOMER_REFERENCE_INFO VALUES ('5','SAVING_ACCOUNT','12345','SOLAPUR','TEMPORY');


SELECT * FROM  CUSTOMER_REFERENCE_INFO;

SHOW TABLES;


-- BANK INFORMATION 

CREATE TABLE BANK_INFO
(
IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(25),
BRANCH_NAME VARCHAR(25),
CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);

INSERT INTO BANK_INFO VALUES('BKGD1234','BANK_OF_MAHARASHRA','NATEPUTE');

INSERT INTO BANK_INFO VALUES('GHJY890765','BANK_OF_INDIA','GURSALE');

INSERT INTO BANK_INFO VALUES('ABXZS12345','BANK_OF_MAHARASHRA','KURWALI');

INSERT INTO BANK_INFO VALUES('VFDER23456','BANK_OF_BARODA','WALCHANDNAGAR');

SELECT * FROM BANK_INFO;

-- ACCOUNT INFORMATION 

CREATE TABLE ACCOUNT_INFO
(
ACCOUNT_NO BIGINT(16),
CUSTOMER_ID VARCHAR(5),
ACCOUNT_TYPE VARCHAR(10),
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
IFSC_CODE VARCHAR(10),
INTEREST DECIMAL(7,2),
INITIAL_DEPOSIT BIGINT(10),
CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
CONSTRAINT ACC_INFO_PERRC_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID),
CONSTRAINT ACC_IFSC_BANK_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
);


INSERT INTO ACCOUNT_INFO VALUE('1234456','1','SAVING','2003-12-11','123452156',123.56,123456);

INSERT INTO ACCOUNT_INFO VALUE('456783','2','DEBIT','2003-11-10','1234523423',100.56,12345656);

INSERT INTO ACCOUNT_INFO VALUE('1156864','5','SAVING','2003-12-11','123452156',123.56,123456);

INSERT INTO ACCOUNT_INFO VALUE('1234456','7','SAVING','2003-12-11','123236',123.56,123456);

SELECT * FROM ACCOUNT_INFO;

SHOW TABLES;


-- THIS CODE ONLY RELATED TO BANK_DATABASE_MANAGMENT_SYSTEM
